### ISSUE TITLE
Looking for a good readme

### ISSUE THREAD

**Issue by vj-abishek** [vj-abishek/saved#2]
This is a chrome extension which shows ![image](https://user-images.githubusercontent.com/43115551/136692748-ff74b5ac-dba5-43fe-a636-70129b7d4e43.png) at the top right

When saved, it shows all saved repos in https://github.com/?save=1

**Comment by Sid-Lais** [comment]
Please assign it to me

**Comment by Sid-Lais** [comment]
What topics are you wanting to be in the readme file?

**Comment by rudratalur** [comment]
please assign this to me and tell what needs to be in Readme.md

**Comment by vj-abishek** [comment]
@rudratalur I think @Sid-Lais got there first. But feel free to work on this
