### ISSUE TITLE
feat: new user interface

### ISSUE THREAD

**Issue by vj-abishek** [vj-abishek/saved#3]
The current UI looks like
![image](https://user-images.githubusercontent.com/43115551/136693124-85a8ff44-cff4-4cc5-a4f1-dfb75b21c4b1.png)

Need some changes to make UI good

Check readme on how to install the extension locally

**Comment by Code-Aditya-14** [comment]
Can you explain it little more, how do you want this.

**Comment by vj-abishek** [comment]
The current UI is in vertical

But I need it in row manner 
Ex: 
| Save | Repo name|
| Save | Repo name|
| Save | Repo name|
| Save | Repo name|


Nxt:
Currently it is rendered like this
![image](https://user-images.githubusercontent.com/43115551/136694296-bb08601d-a3be-4847-8b99-e0394f73bea6.png)

**Comment by Code-Aditya-14** [comment]
I can give it a try.

**Comment by vj-abishek** [comment]
![image](https://user-images.githubusercontent.com/43115551/136695032-072a7612-f092-4de8-9f17-28916fc53ed2.png)

Something like. The content should be inside a card

Inspect the element and see what GitHub uses. Use the same classes.

**Comment by vj-abishek** [comment]
@Code-Aditya-14 are you working on this?

**Comment by vj-abishek** [comment]
@Code-Aditya-14 If you think it is hard, you can try the next issue, which is easier than this!

**Comment by vj-abishek** [comment]
What is the error?

**Comment by vj-abishek** [comment]
@Code-Aditya-14 I fixed the UI tag issue. You can now work on the design

Fork and pull those latest changes and start to work!

**Comment by Code-Aditya-14** [comment]
@vj-abishek I had created the pull request. Please let me know if it needs some more changes.
