### ISSUE TITLE
feat: Unsave functionality

### ISSUE THREAD

**Issue by vj-abishek** [vj-abishek/saved#5]
Task : implement Unsave function

You need to change this line

 https://github.com/vj-abishek/saved/blob/8ca61684024e0e072c9663cde25634aaf545bb1e/public/App.js#L60

  Docs on how to delete a collection in dexiedb 
 https://dexie.org/docs/Collection/Collection.delete()

After when u delete the collection, you need to update the the save button (back to normal)

Use this condition while deleting a collection

https://github.com/vj-abishek/saved/blob/8ca61684024e0e072c9663cde25634aaf545bb1e/public/App.js#L2

**Comment by Nithin005** [comment]
PR created
